# Generated by Django 5.2.12 on 2026-04-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Histroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.TextField()),
                ('value_2', models.TextField()),
                ('value_3', models.TextField()),
            ],
        ),
    ]
