# Generated by Django 5.2.12 on 2026-04-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='histroy',
            name='operator',
            field=models.CharField(default='+', max_length=1),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='value_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='value_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='histroy',
            name='value_3',
            field=models.FloatField(),
        ),
    ]
